"""Add composite index for customer status created_at

Revision ID: 167f0257c7b0
Revises: b976c5576159
Create Date: 2026-01-19 12:27:08.609034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '167f0257c7b0'
down_revision: Union[str, Sequence[str], None] = 'b976c5576159'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('id_customer_status_created', 'orders', ['customer_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('id_customer_status_created', table_name='orders')
    # ### end Alembic commands ###
