"""delete index temporally

Revision ID: 562e100fa50f
Revises: befe674e3e61
Create Date: 2026-01-19 12:03:34.446757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '562e100fa50f'
down_revision: Union[str, Sequence[str], None] = 'befe674e3e61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('id_customer_status_created'), table_name='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('id_customer_status_created'), 'orders', ['customer_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###
