# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: payment.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'payment.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpayment.proto\x12\x07payment\"+\n\x17GetPaymentStatusRequest\x12\x10\n\x08order_id\x18\x01 \x01(\x05\"x\n\x18GetPaymentStatusResponse\x12\x10\n\x08order_id\x18\x01 \x01(\x05\x12\x0e\n\x06status\x18\x02 \x01(\t\x12\x12\n\npayment_id\x18\x03 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x04 \x01(\x01\x12\x16\n\x0epayment_method\x18\x05 \x01(\t2i\n\x0ePaymentService\x12W\n\x10GetPaymentStatus\x12 .payment.GetPaymentStatusRequest\x1a!.payment.GetPaymentStatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'payment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETPAYMENTSTATUSREQUEST']._serialized_start=26
  _globals['_GETPAYMENTSTATUSREQUEST']._serialized_end=69
  _globals['_GETPAYMENTSTATUSRESPONSE']._serialized_start=71
  _globals['_GETPAYMENTSTATUSRESPONSE']._serialized_end=191
  _globals['_PAYMENTSERVICE']._serialized_start=193
  _globals['_PAYMENTSERVICE']._serialized_end=298
# @@protoc_insertion_point(module_scope)
